name: Keep Streamlit App Awake

on:
  schedule:
    # Runs every 10 hours
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Ping Streamlit App
        run: curl -I ${{ secrets.STREAMLIT_APP_URL }}
