name: Keep Streamlit App Awake

on:
  schedule:
    - cron: "0 */3 * * *"   # every 3 hours (UTC)
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl the app
        run: |
          curl -sS -L "hhttps://5gjobs.streamlit.app/main" >/dev/null
